src/EventListener/PostQueryBuilderSubscriber.php
tests/Controller/RequestParametersTest.php
tests/Fixtures/AppTestBundle/DataFixtures/ORM/LoadProducts.php
tests/Fixtures/AppTestBundle/Entity/FunctionalTests/Product.php

updated filterQueryBuilder function by adding two conditions : the NULL and the NOT NULL value in the filters.

Handling the null/not null value

---

.coveralls.yml
.editorconfig
.travis.yml
README.md
phpunit.xml.dist
src/Configuration/MenuConfigPass.php
src/Configuration/ShortFormTypeConfigPass.php
src/Controller/AdminController.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/EasyAdminExtensionExtension.php
src/EasyAdminExtensionBundle.php
src/Form/Transformer/RestoreRolesTransformer.php
src/Form/Type/Security/AdminRolesType.php
src/Form/Type/Transformer/RestoreRolesTransformer.php
src/Model/AdminGroup.php
src/Model/AdminUser.php
src/Resources/config/doctrine-mapping/AdminGroup.orm.xml
src/Resources/config/doctrine-mapping/AdminUser.orm.xml
src/Resources/config/services.xml
src/Resources/views/form/bootstrap_3_layout.html.twig
src/Resources/views/form/checkbox_tree.html.twig
src/Security/AdminAuthorizationChecker.php
src/Security/EditableRolesBuilder.php
src/Twig/CheckboxTreeExtension.php
tests/Fixtures/App/AppKernel.php
tests/Form/Transformer/RestoreRolesTransformerTest.php

- Add a minimal structure for user/group and roles
- Add form types for roles
- Configure required roles for action, and minimum_role for entire admin
- Deny access to actions if required role is not granted

[WIP] Admin users and role management

---

src/Configuration/EmbeddedListSortConfigPass.php
src/Resources/config/services.xml
tests/Controller/EmbeddedListTest.php
tests/Fixtures/App/config/config_embedded_list.yml

Sort embedddList according to list config

---

src/Configuration/EmbeddedListViewConfigPass.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/EasyAdminExtensionExtension.php
src/Resources/config/services.xml
src/Resources/views/default/embedded_list.html.twig
tests/Configuration/EmbeddedListViewConfigPassTest.php
tests/Controller/EmbeddedListTest.php
tests/Fixtures/App/config/config_embedded_list.yml

Add embedded_list open_new_tab config option

---

src/Form/Type/EasyAdminEmbeddedListType.php
src/Resources/views/default/field_embedded_list.html.twig
src/Resources/views/form/bootstrap_3_layout.html.twig

Allow sorting embedded list by instance

---

README.md
src/Form/Type/EasyAdminEmbeddedListType.php
src/Helper/EmbeddedListHelper.php
src/Resources/config/services.xml
tests/Controller/EmbeddedListTest.php
tests/Fixtures/App/config/config_embedded_list.yml
tests/Fixtures/AppTestBundle/DataFixtures/ORM/LoadProducts.php
tests/Fixtures/AppTestBundle/Entity/FunctionalTests/Category.php
tests/Fixtures/AppTestBundle/Entity/FunctionalTests/Product.php

Embedded lists guesser

---

README.md
src/Resources/views/default/show_vertical.html.twig

Add template show vertical boostrap

Add template show vertical boostrap

---

src/Resources/translations/EasyAdminBundle.en.xlf

fix translations

---

src/Resources/translations/EasyAdminBundle.es.xlf

translation es

---

README.md

https://symfony.com/doc/master/bundles/EasyAdminBundle/book/complex-dynamic-backends.html

change to easy_admin_bundle

---

src/Resources/translations/EasyAdminBundle.hu.xlf

I added Hungarian translation.

Add Hungarian translation

---

src/Controller/AdminController.php
src/Resources/views/default/embedded_list.html.twig
src/Resources/views/default/list.html.twig
src/Resources/views/default/show.html.twig
src/Resources/views/form/bootstrap_3_layout.html.twig
src/Security/AdminAuthorizationChecker.php
src/Twig/AdminAuthorizationExtension.php
tests/Helper/MenuHelperTest.php

Authorization checker compatible with security voters

---

src/Form/Type/Extension/EasyAdminAutocompleteTypeExtension.php
src/Resources/public/js/autocomplete-create.js
src/Resources/public/js/easyadmin-extension.js

Js, neccesary method serializeForm.
Entity name fix.

js and entity name

---

src/Resources/translations/EasyAdminBundle.zh_CN.xlf
src/Resources/translations/EasyAdminBundle.zh_TW.xlf

add  chinese translation

---

src/Resources/views/default/list.html.twig

By pressing anywhere on the panel-heading show form filters

By pressing anywhere on the panel-heading show form filters

---

src/Configuration/ListFormFiltersConfigPass.php

Fix default ListFilterForm config for -to-one associations

---

src/Form/Type/Extension/EasyAdminAutocompleteTypeExtension.php
src/Resources/views/default/embedded_list.html.twig

Remove some sf 4.2 and twig 2.x deprecations

---

src/Controller/EasyAdminController.php

EmbeddedList keeps dql_filter configurations

---

src/Configuration/ListFormFiltersConfigPass.php

Fixes #119
@BenjaminTappnad Can you try this branch and tell me if it solves your issue ?

Autoset filter ChoiceType options for associations

---

src/Helper/EmbeddedListHelper.php

Logging a more descriptive solution when many matching entities

---

src/Security/AdminAuthorizationChecker.php
tests/Controller/UserRolesTest.php

Should fix #154 
@rodrigobb Can you test this branch please ?

Fix logged message in case of 403

---

src/Helper/EmbeddedListHelper.php

cf. https://insight.symfony.com/projects/a7179df5-4ed7-468c-899c-891535dbe802/analyses/279?status=violations#811008241

Checks the existence of a public getId method

---

src/Model/AdminUser.php

Remove UserInterface SF 5.4 deprecations
